/// All functions from man tmux "Clients and Sessions" listed below
/// [man tmux](http://man7.org/linux/man-pages/man1/tmux.1.html#CLIENTS_AND_SESSIONS)
pub mod attach_session;
pub mod detach_client;
pub mod has_session;
pub mod kill_server;
pub mod kill_session;
pub mod list_clients;
pub mod list_commands;
pub mod list_sessions;
pub mod lock_client;
pub mod lock_session;
pub mod new_session;
pub mod refresh_client;
pub mod rename_session;
pub mod show_messages;
pub mod source_file;
pub mod start_server;
pub mod suspend_client;
pub mod switch_client;
